### ISSUE TITLE
snooze doesn't know the 1st of April

### ISSUE THREAD

**Issue by koryphaee** [chneukirchen/snooze#2]
So I tried to make a small script that would disable my Internet on every 1st of April since I kinda don't like April Fools' jokes.

This is what I used to test the command:
`snooze -n -m 4 -d 1`
but it returns
`no satisfying date found within a year`

These work flawless:
`snooze -n -m 3 -d 1`
`snooze -n -m 5 -d 1`
`snooze -n -m 4 -d 2`

Also when I do this:
`snooze -n -m 4 -d 1-2`
It returns the 2nd of April five times.

Is this an April Fools' joke itself or just a weird bug?

**Comment by chneukirchen** [comment]
Thanks for the report, it is indeed a bug, related to DST change.

I'm working on a fix, but it requires some significant reworking.

**Comment by koryphaee** [comment]
It's working correctly now. Thanks for the quick response and fix. I'll close the issue.
